# SPDX-License-Identifier: GPL-2.0
#
# s390x backend host-side (os-Linux) objects for UML.

obj-y = registers.o mcontext.o machinename.o

USER_OBJS := $(obj-y)

include $(srctree)/arch/um/scripts/Makefile.rules
